# Generated by Django 2.1.5 on 2019-02-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='cod_barra',
            field=models.IntegerField(unique=True),
        ),
    ]
