# Generated by Django 2.1.5 on 2019-02-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20190208_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='produtos_photos'),
        ),
    ]
