# Generated by Django 2.1.5 on 2019-02-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20190202_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos_photos'),
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos_photos'),
        ),
    ]
