# Generated by Django 2.1.5 on 2019-02-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20190208_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='cod_barra',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
