# Generated by Django 2.1.5 on 2019-02-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20190202_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=9),
            preserve_default=False,
        ),
    ]
