# Generated by Django 2.1.5 on 2019-02-04 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0003_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
                ('etc', models.CharField(blank=True, max_length=144, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='veiculos_photos')),
                ('proprietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Person')),
            ],
        ),
    ]
